# Generated by Django 5.0.3 on 2024-03-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_medicine', models.CharField(max_length=100)),
                ('initial_stock', models.IntegerField()),
                ('stock_in', models.IntegerField()),
                ('stock_out', models.IntegerField()),
                ('final_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='Initial_stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='Stock_in',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='Stock_out',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
