# Generated by Django 5.0.3 on 2024-03-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0002_inventoryreport_medicine_initial_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euser', models.CharField(max_length=100)),
                ('epassw', models.CharField(max_length=100)),
            ],
        ),
    ]
