# Generated by Django 5.0.3 on 2024-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='econtact_no',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
