# Generated by Django 5.0.3 on 2024-03-16 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0005_rename_total_stock_medicine_final_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 3, 16, 14, 41, 44, 41409, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
