# Generated by Django 5.0.3 on 2024-03-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0006_employee_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='final_stock',
        ),
    ]
