# Generated by Django 5.0.3 on 2024-03-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0008_trackmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in', models.IntegerField()),
                ('stock_out', models.IntegerField()),
                ('total_stock', models.IntegerField()),
                ('total_sales', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medisync.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Stocktrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='trackMedicine',
        ),
    ]
