# Generated by Django 5.0.3 on 2024-03-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('medisync', '0009_medicinehistory_stocktrack_delete_trackmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='signIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
