# Generated by Django 5.0.3 on 2024-03-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0010_signin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signin',
            table='SignIn',
        ),
    ]
