# Generated by Django 5.0.3 on 2024-03-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0011_alter_signin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='Medicine',
        ),
    ]
