# Generated by Django 5.0.3 on 2024-03-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0012_alter_medicine_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
