# Generated by Django 5.0.3 on 2024-03-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0015_invendetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invendetails',
            name='batch_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invendetails',
            name='medicine_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invendetails',
            name='supplier_id',
            field=models.CharField(max_length=100),
        ),
    ]
