# Generated by Django 5.0.3 on 2024-03-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisync', '0017_alter_invendetails_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_id', models.CharField(max_length=100)),
                ('supplier_id', models.CharField(max_length=100)),
                ('quantity_ordered', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('supplier_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Purchase Order',
            },
        ),
    ]
